/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.52
 * Generated at: 2018-09-27 15:25:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.io.*;
import java.lang.*;
import java.sql.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.lang");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("     \r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>HOTEL_MANAGEMENT</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function register() {\r\n");
      out.write("\t\r\n");
      out.write("\tvar id=document.registrationform.id.value;\r\n");
      out.write("\tvar name=document.registrationform.name.value;\r\n");
      out.write("\tvar email=document.registrationform.email.value;\r\n");
      out.write("\tvar p=document.registrationform.pass1.value;\r\n");
      out.write("\tvar c=document.registrationform.pass2.value;\r\n");
      out.write("\tvar state=document.registrationform.state.value;\r\n");
      out.write("\tvar dist=document.registrationform.dist.value;\r\n");
      out.write("\tvar cons=document.registrationform.cons.value;\r\n");
      out.write("\tvar attherateposition=email.indexOf(\"@\");  \r\n");
      out.write("\tvar dotposition=email.lastIndexOf(\".\");\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t   if(id==null ||id==\"\"){  \r\n");
      out.write("\t\t  alert(\"id can't be empty\");  \r\n");
      out.write("\t\t  return false;  \r\n");
      out.write("\t\t} \r\n");
      out.write("\t   else if(c==null||c==\"\"){\r\n");
      out.write("\t\t   alert(\"password can't be empty\");\r\n");
      out.write("\t\t   return false;\r\n");
      out.write("\t   }\r\n");
      out.write("\t   else if(p.length<6){\r\n");
      out.write("\t\t   alert(\"password length should be atleast 6\");\r\n");
      out.write("\t\t   return false;\r\n");
      out.write("\t   }\r\n");
      out.write("\t    \r\n");
      out.write("\t    else if(p!=c){\r\n");
      out.write("\t    \talert(\"password must be same\");\r\n");
      out.write("\t    \treturn false;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    else if(name==null ||name==\"\"){  \r\n");
      out.write("\t\t\t  alert(\"ename can't be empty\");  \r\n");
      out.write("\t\t\t  return false; \r\n");
      out.write("\t    }\r\n");
      out.write("\t    else if(state==null||state==\"\"){\r\n");
      out.write("\t    \talert(\"State field can't be empty\");\r\n");
      out.write("\t    \treturn false;\r\n");
      out.write("\t    }\r\n");
      out.write("\t   else if(dist==null||dist==\"\"){\r\n");
      out.write("\t    \talert(\"District field can't be empty\");\r\n");
      out.write("\t    \treturn false;\r\n");
      out.write("\t    }\r\n");
      out.write("\t     else  if(cons==null||cons==\"\"){\r\n");
      out.write("\t    \talert(\"Constituency field can't be empty\");\r\n");
      out.write("\t    \treturn false;\r\n");
      out.write("\t    }\r\n");
      out.write("\t     else if (attherateposition<1 || dotposition<attherateposition+2 || dotposition+2>=email.length){  \r\n");
      out.write("\t\t     alert(\"Please enter a valid e-mail address \\n @:\"+attherateposition+\"\\n .:\"+dotposition);  \r\n");
      out.write("\t\t     return false;  \r\n");
      out.write("\t\t     }   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");


String id=request.getParameter("id");
String name=request.getParameter("name");
String email=request.getParameter("email");
String password=request.getParameter("pass1");
String state=request.getParameter("state");
String dist=request.getParameter("dist");
String cons=request.getParameter("cons");


try
{
	
	
	//register the driver
	
	Class.forName("oracle.jdbc.driver.OracleDriver");
	
	Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","mubeen","chikara");
	
	
	
	PreparedStatement ps=con.prepareStatement("insert into voting values(?,?,?,?,?,?,?)");
	
	
	ps.setString(1, id);
	
	ps.setString(2, name);

	ps.setString(3, email);
	ps.setString(4, password);
	ps.setString(5, state);
	ps.setString(6, dist);
	ps.setString(7,cons);
	
	
int res=	ps.executeUpdate();



	if(res>0)
	{
		System.out.println("Congrates Your Details Are Registered");
		
	}
	else
	{
		System.out.println("Sorry Your Details Are  Not Registered");
	}
}
catch(Exception e)
{
	
	e.printStackTrace();
}


      out.write("\r\n");
      out.write("\r\n");
      out.write("<body background=\"D:\\mini_project_practice\\Ems\\WebContent\\images\\vote220.jpg\"width=\"1300\">\r\n");
      out.write("<form name=\"registrationform\"action=\"Voter_reg.jsp\" method=\"post\"  onsubmit=\"return register()\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("<img alt=\"vote\" src=\"D:\\mini_project_practice\\Ems\\WebContent\\images\\vote11.png\"height=\"100\"width=\"720\">\r\n");
      out.write("</div>\r\n");
      out.write("<b><hr></b>\r\n");
      out.write("<div>\r\n");
      out.write("<marquee direction=\"left\"><font size=\"4\"><font color=\"Ivory\">\r\n");
      out.write("<span><B>BE SMART TO DO YOUR PART,VOTE.............</B></span>\r\n");
      out.write("</font></font></marquee>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"v\"align=\"center\">\r\n");
      out.write("\r\n");
      out.write("<legend><b><font size=\"8\">HOTEL MANAGEMENT</font></b></legend>\r\n");
      out.write("<table border=\"4\"><font color=\"blue\">\r\n");
      out.write("<tr>\r\n");
      out.write("\r\n");
      out.write("<td><font color=\"red\">ID</font></td>\r\n");
      out.write("<td><input type=\"text\"name=\"id\"placeholder=\"Enter ID\">\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td><font color=\"yellow\">Name</font></td>\r\n");
      out.write("<td><input type=\"text\" name=\"name\"placeholder=\"Enter Name\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td><font color=\"yellow\">\r\n");
      out.write("Email</font>\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type=\"email\" name=\"email\"placeholder=\"Enter Email\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td><font color=\"yellow\">\r\n");
      out.write("Password</font>\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type=\"password\"name=\"pass1\"placeholder=\"Enter password\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td><font color=\"yellow\">\r\n");
      out.write("Confirm Password</font>\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type=\"password\"name=\"pass2\"placeholder=\"Confirm password\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td><font color=\"yellow\">\r\n");
      out.write("State</font>\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<input text=\"text\"name=\"state\"placeholder=\"Telangana\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td><font color=\"yellow\">\r\n");
      out.write("District</font>\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type=\"text\"name=\"dist\"placeholder=\"Hyderabad\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td ><font color=\"yellow\">\r\n");
      out.write("Assembly/Parliamentary/Constituency</font>\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type=\"text\"name=\"cons\"placeholder=\"Enter Constituency\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td><font color=\"yellow\">File:</font></td>\r\n");
      out.write(" <td> <input type=\"file\" name=\"pic\" accept=\"image/*\">\r\n");
      out.write("  \r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td colspan=\"2\"align=\"center\">\r\n");
      out.write("<input type=\"submit\"name=\"submit\"value=\"Register\"></span>\r\n");
      out.write("<input type=\"reset\"name=\"reset\"value=\"Cancel\"></span>\r\n");
      out.write("</td>\r\n");
      out.write("</tr></font></table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("<video width=\"1350\"height=\"350\"  autoplay>\r\n");
      out.write("<source src=\"D:\\mini_project_practice\\Ems\\WebContent\\video\\movie.mp4\" type=\"video/mp4\"></source>\r\n");
      out.write("</video>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
